version: "3.9"

services:
  backend:
   image: tamarae/academia-backend:latest
   container_name: backend
   restart: always
   ports:
      - 5000:5000
  frontend:
   image: tamarae/academia-frontend:v1f
   container_name: frontend
   restart: always
   ports:
      - 80:80